// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { B64String } from "./B64String";
import type { QueryableMsg } from "./QueryableMsg";
import type { ReplyWS } from "./ReplyWS";
import type { SampleWS } from "./SampleWS";

export type DataMsg = { "PublisherPut": { id: string, payload: B64String, attachment: B64String | null, encoding: string | null, } } | { "Sample": [SampleWS, string] } | { "GetReply": ReplyWS } | { "Queryable": QueryableMsg };
