// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OwnedKeyExprWrapper } from "./OwnedKeyExprWrapper.js";

export type LivelinessMsg = { "DeclareToken": { key_expr: OwnedKeyExprWrapper, id: string, } } | { "UndeclareToken": string } | { "DeclareSubscriber": { key_expr: OwnedKeyExprWrapper, id: string, history: boolean, } } | { "UndeclareSubscriber": string } | { "Get": { key_expr: OwnedKeyExprWrapper, id: string, timeout: number | undefined, } };
