// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { B64String } from "./B64String";
import type { OwnedKeyExprWrapper } from "./OwnedKeyExprWrapper";

export type QueryReplyVariant = { "Reply": { key_expr: OwnedKeyExprWrapper, payload: B64String, } } | { "ReplyErr": { payload: B64String, } } | { "ReplyDelete": { key_expr: OwnedKeyExprWrapper, } };
