// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OwnedKeyExprWrapper } from "./OwnedKeyExprWrapper.js";

export type QueryWS = { query_uuid: string, key_expr: OwnedKeyExprWrapper, parameters: string, encoding: string | null, attachment: string | undefined, payload: string | undefined, };
