// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { B64String } from "./B64String.js";

export type ReplyErrorWS = { payload: B64String, encoding: string, };
