// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { B64String } from "./B64String.js";
import type { OwnedKeyExprWrapper } from "./OwnedKeyExprWrapper.js";
import type { SampleKindWS } from "./SampleKindWS.js";

export type SampleWS = { key_expr: OwnedKeyExprWrapper, value: B64String, kind: SampleKindWS, encoding: string, timestamp: string | null, congestion_control: number, priority: number, express: boolean, attachement: B64String | null, };
