// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SessionInfo = { zid: string, z_routers: Array<string>, z_peers: Array<string>, };
